name: Sync PyramidStore Projects to py1 and py2

on:
  schedule:
    - cron: '0 16 */2 * *'  # 每两天北京时间 00:00 运行
  workflow_dispatch:         # 支持手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repository
        uses: actions/checkout@v3

      - name: Set up Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Sync PyramidStore to py1/
        run: |
          rm -rf py1
          git clone --depth=1 https://github.com/sowahsun/PyramidStore.git py1
          rm -rf py1/.git

      - name: Sync PyramidStorejjbjj to py2/
        run: |
          rm -rf py2
          git clone --depth=1 https://github.com/skyboy77/PyramidStorejjbjj.git py2
          rm -rf py2/.git

      - name: Commit and push changes
        run: |
          git add py1 py2
          git commit -m "Auto-sync py1 and py2 from upstream GitHub projects [skip ci]" || echo "No changes"
          git push origin main

  cleanup:
    runs-on: ubuntu-latest
    needs: sync
    steps:
      - name: Delete old workflow runs, keep last 10
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          retain_days: 0
          keep_minimum_runs: 10
