name: Sync PyramidStore Projects

on:
  schedule:
    - cron: '0 16 */2 * *'  # 每两天北京时间 00:00 运行
  workflow_dispatch:         # 支持手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your own repository
        uses: actions/checkout@v3

      - name: Set up Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # 同步 sowahsun/PyramidStore 到 py/py1/
      - name: Sync PyramidStore to py/py1/
        run: |
          rm -rf py/py1
          git clone --depth=1 https://github.com/sowahsun/PyramidStore.git py/py1
          rm -rf py/py1/.git

      # 同步 skyboy77/PyramidStorejjbjj 到 py/py2/
      - name: Sync PyramidStorejjbjj to py/py2/
        run: |
          rm -rf py/py2
          git clone --depth=1 https://github.com/skyboy77/PyramidStorejjbjj.git py/py2
          rm -rf py/py2/.git

      - name: Commit and push changes
        run: |
          git add py/py1 py/py2
          git commit -m "Auto-sync py/py1 and py/py2 from upstream projects [skip ci]" || echo "No changes"
          git push origin main
